# Generated by Django 5.2.5 on 2026-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_app", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="complaints/"),
        ),
    ]
