# Generated by Django 5.2.5 on 2026-04-02 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_app", "0003_complaint_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
